server:
  port: 8082

spring:
  r2dbc:
    url: r2dbcs:mysql://localhost:3303/cource_db?serverTimezone=Europe/Moscow&useUnicode=yes&characterEncoding=UTF-8
    username: user
    password: password
  liquibase:
    enabled: true
    change-log: "classpath:/changelog/changelog.xml"
    url: jdbc:mysql://localhost:3303/cource_db?serverTimezone=Europe/Moscow&useUnicode=yes&characterEncoding=UTF-8
    user: user
    password: password
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  kafka.consumer:
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    bootstrap-servers: localhost:29092
    properties:
      spring:
        json:
          trusted:
            packages: "*"
