server:
  port: 8081

spring:
  r2dbc:
    url: r2dbcs:mysql://localhost:3304/student_db?serverTimezone=Europe/Moscow&useUnicode=yes&characterEncoding=UTF-8
    username: user
    password: password
  liquibase:
    enabled: true
    change-log: "classpath:/changelog/changelog.xml"
    url: jdbc:mysql://localhost:3304/student_db?serverTimezone=Europe/Moscow&useUnicode=yes&characterEncoding=UTF-8
    user: user
    password: password
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  kafka.producer:
    bootstrap-servers: localhost:29092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
